language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

before_install:
  - wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
  - sudo dpkg -i puppetlabs-release-precise.deb
  - sudo apt-get update -qq
  - sudo apt-get install -y puppet
  - sudo git clone https://github.com/puppetlabs/puppetlabs-ntp.git /etc/puppet/modules/ntp

script: 'bundle exec rake'

notifications:
  email:
    on_failure: change
    on_success: never

