language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

before_install:
  - sudo scripts/pretest.sh

script: 'bundle exec rake'

notifications:
  email:
    on_failure: change
    on_success: never

