language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

install:
  - pwd
  - ls
  - sudo ./scripts/ubuntu12.04-puppet.sh
  - sudo ./scripts/pretest.sh

script: 'bundle exec rake'

notifications:
  email:
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: f73a867bdb9f7839256dbf50604585592eecf50f5fb0ea09c0783eb27649e6f2
